class QuranResources {
  static List<String> QuranArabicList = [
    "الفاتحة",
    "البقرة",
    "آل عمران",
    "النساء",
    "المائدة",
    "الأنعام",
    "الأعراف",
    "الأنفال",
    "التوبة",
    "يونس",
    "هود",
    "يوسف",
    "الرعد",
    "إبراهيم",
    "الحجر",
    "النحل",
    "الإسراء",
    "الكهف",
    "مريم",
    "طه",
    "الأنبياء",
    "الحج",
    "المؤمنون",
    "النور",
    "الفرقان",
    "الشعراء",
    "النمل",
    "القصص",
    "العنكبوت",
    "الروم",
    "لقمان",
    "السجدة",
    "الأحزاب",
    "سبأ",
    "فاطر",
    "يس",
    "الصافات",
    "ص",
    "الزمر",
    "غافر",
    "فصلت",
    "الشورى",
    "الزخرف",
    "الدخان",
    "الجاثية",
    "الأحقاف",
    "محمد",
    "الفتح",
    "الحجرات",
    "ق",
    "الذاريات",
    "الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "الطلاق",
    "التحريم",
    "الملك",
    "القلم",
    "الحاقة",
    "المعارج",
    "نوح",
    "الجن",
    "المزمل",
    "المدثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "النبأ",
    "النازعات",
    "عبس",
    "التكوير",
    "الإنفطار",
    "المطففين",
    "الإنشقاق",
    "البروج",
    "الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العاديات",
    "القارعة",
    "التكاثر",
    "العصر",
    "الهمزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس",
  ];
  static List<String> QuranEnglishList = [
    "Al-Fatihah (The Opening)",
    "Al-Baqarah (The Cow)",
    "Aal Imran (The Family of Imran)",
    "An-Nisa (Women)",
    "Al-Ma’idah (The Table Spread)",
    "Al-An’am (The Cattle)",
    "Al-A’raf (The Heights)",
    "Al-Anfal (The Spoils of War)",
    "At-Tawbah (Repentance)",
    "Yunus (Jonah)",
    "Hud",
    "Yusuf (Joseph)",
    "Ar-Ra’d (The Thunder)",
    "Ibrahim (Abraham)",
    "Al-Hijr (The Rocky Tract)",
    "An-Nahl (The Bee)",
    "Al-Isra (The Night Journey)",
    "Al-Kahf (The Cave)",
    "Maryam (Mary)",
    "Ta-Ha",
    "Al-Anbiya (The Prophets)",
    "Al-Hajj (The Pilgrimage)",
    "Al-Mu’minun (The Believers)",
    "An-Nur (The Light)",
    "Al-Furqan (The Criterion)",
    "Ash-Shu’ara (The Poets)",
    "An-Naml (The Ant)",
    "Al-Qasas (The Stories)",
    "Al-Ankabut (The Spider)",
    "Ar-Rum (The Romans)",
    "Luqman",
    "As-Sajdah (The Prostration)",
    "Al-Ahzab (The Confederates)",
    "Saba (Sheba)",
    "Fatir (The Originator)",
    "Ya-Sin",
    "As-Saffat (Those Ranged in Rows)",
    "Sad",
    "Az-Zumar (The Groups)",
    "Ghafir (The Forgiver)",
    "Fussilat (Explained in Detail)",
    "Ash-Shura (Consultation)",
    "Az-Zukhruf (Ornaments of Gold)",
    "Ad-Dukhan (The Smoke)",
    "Al-Jathiyah (The Crouching)",
    "Al-Ahqaf (The Wind-Curved Sandhills)",
    "Muhammad",
    "Al-Fath (The Victory)",
    "Al-Hujurat (The Rooms)",
    "Qaf",
    "Adh-Dhariyat (The Winnowing Winds)",
    "At-Tur (The Mount)",
    "An-Najm (The Star)",
    "Al-Qamar (The Moon)",
    "Ar-Rahman (The Beneficent)",
    "Al-Waqi’ah (The Inevitable)",
    "Al-Hadid (The Iron)",
    "Al-Mujadila (The Pleading Woman)",
    "Al-Hashr (The Exile)",
    "Al-Mumtahanah (She that is to be examined)",
    "As-Saff (The Ranks)",
    "Al-Jumu’ah (Friday)",
    "Al-Munafiqun (The Hypocrites)",
    "At-Taghabun (Mutual Disillusion)",
    "At-Talaq (Divorce)",
    "At-Tahrim (The Prohibition)",
    "Al-Mulk (The Sovereignty)",
    "Al-Qalam (The Pen)",
    "Al-Haqqah (The Reality)",
    "Al-Ma’arij (The Ascending Stairways)",
    "Nuh (Noah)",
    "Al-Jinn",
    "Al-Muzzammil (The Enshrouded One)",
    "Al-Muddaththir (The Cloaked One)",
    "Al-Qiyamah (The Resurrection)",
    "Al-Insan (Man)",
    "Al-Mursalat (The Emissaries)",
    "An-Naba (The Tidings)",
    "An-Nazi’at (Those who drag forth)",
    "Abasa (He frowned)",
    "At-Takwir (The Overthrowing)",
    "Al-Infitar (The Cleaving)",
    "Al-Mutaffifin (Defrauding)",
    "Al-Inshiqaq (The Splitting Open)",
    "Al-Buruj (The Mansions of the Stars)",
    "At-Tariq (The Morning Star)",
    "Al-A’la (The Most High)",
    "Al-Ghashiyah (The Overwhelming)",
    "Al-Fajr (The Dawn)",
    "Al-Balad (The City)",
    "Ash-Shams (The Sun)",
    "Al-Lail (The Night)",
    "Ad-Duhaa (The Morning Hours)",
    "Ash-Sharh (The Relief)",
    "At-Tin (The Fig)",
    "Al-‘Alaq (The Clot)",
    "Al-Qadr (The Power)",
    "Al-Bayyina (The Clear Proof)",
    "Az-Zalzalah (The Earthquake)",
    "Al-‘Adiyat (The Chargers)",
    "Al-Qari’ah (The Calamity)",
    "At-Takathur (The Rivalry in world increase)",
    "Al-‘Asr (The Declining Day)",
    "Al-Humazah (The Traducer)",
    "Al-Fil (The Elephant)",
    "Quraish",
    "Al-Ma’un (Small Kindnesses)",
    "Al-Kawthar (Abundance)",
    "Al-Kafirun (The Disbelievers)",
    "An-Nasr (Divine Support)",
    "Al-Masad (The Palm Fiber)",
    "Al-Ikhlas (Sincerity)",
    "Al-Falaq (The Daybreak)",
    "An-Nas (Mankind)",
  ];
  static List<String> versesNumberList = [
    "7",
    "286",
    "200",
    "176",
    "120",
    "165",
    "206",
    "75",
    "129",
    "109",
    "123",
    "111",
    "43",
    "52",
    "99",
    "128",
    "111",
    "110",
    "98",
    "135",
    "112",
    "78",
    "118",
    "64",
    "77",
    "227",
    "93",
    "88",
    "69",
    "60",
    "34",
    "30",
    "73",
    "54",
    "45",
    "83",
    "182",
    "88",
    "75",
    "85",
    "54",
    "53",
    "89",
    "59",
    "37",
    "35",
    "38",
    "29",
    "18",
    "45",
    "60",
    "49",
    "62",
    "55",
    "78",
    "96",
    "29",
    "22",
    "24",
    "13",
    "14",
    "11",
    "11",
    "18",
    "12",
    "12",
    "30",
    "52",
    "52",
    "44",
    "28",
    "28",
    "20",
    "56",
    "40",
    "31",
    "50",
    "40",
    "46",
    "42",
    "29",
    "19",
    "36",
    "25",
    "22",
    "17",
    "19",
    "26",
    "30",
    "20",
    "15",
    "21",
    "11",
    "8",
    "8",
    "19",
    "5",
    "8",
    "8",
    "11",
    "11",
    "8",
    "3",
    "9",
    "5",
    "4",
    "7",
    "3",
    "6",
    "3",
    "5",
    "4",
    "5",
    "6",
  ];
}
